"""empty message

Revision ID: 50b8c91ec8ac
Revises: 
Create Date: 2018-08-17 21:02:37.157262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b8c91ec8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('mark_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['expenditure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenditure_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenditure_type')
    op.drop_table('expenditure')
    # ### end Alembic commands ###
